# Generated by Django 3.0.7 on 2020-06-25 01:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form', to='home.HomePage'),
        ),
    ]
