# Generated by Django 3.0.7 on 2020-06-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_formpage_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPageGalleryImage',
            new_name='ExpertiseItem',
        ),
    ]
