# Generated by Django 3.0.7 on 2020-06-27 19:36

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200627_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblock',
            options={},
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_descriptions', to='home.ServiceBlock'),
        ),
    ]
