# Generated by Django 3.0.7 on 2020-06-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200627_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblock',
            name='html_id',
            field=models.CharField(blank=True, help_text='Add one word describing this section; should be all lowercase', max_length=20, null=True, verbose_name='ID'),
        ),
    ]
