# Generated by Django 3.0.7 on 2020-06-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_serviceblock_html_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblock',
            name='html_id',
            field=models.CharField(default='', help_text='Add one word describing this section; should be all lowercase', max_length=20, verbose_name='ID'),
        ),
    ]
